// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CreateTransactionParams is parameters of CreateTransaction operation.
type CreateTransactionParams struct {
	// The type of source that the request came from (game, server, or payment).
	SourceType CreateTransactionSourceType
}

func unpackCreateTransactionParams(packed middleware.Parameters) (params CreateTransactionParams) {
	{
		key := middleware.ParameterKey{
			Name: "Source-Type",
			In:   "header",
		}
		params.SourceType = packed[key].(CreateTransactionSourceType)
	}
	return params
}

func decodeCreateTransactionParams(args [0]string, argsEscaped bool, r *http.Request) (params CreateTransactionParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Source-Type.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Source-Type",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SourceType = CreateTransactionSourceType(c)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.SourceType.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Source-Type",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}
