// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTransaction implements CreateTransaction operation.
//
// Process and save an incoming request.
//
// POST /transactions
func (UnimplementedHandler) CreateTransaction(ctx context.Context, req *Transaction, params CreateTransactionParams) (r CreateTransactionRes, _ error) {
	return r, ht.ErrNotImplemented
}
