version: '3.9'
services:
  app:
    container_name: golang_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    tty: true
    env_file:
      - .env
    image: tracker:latest
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_PORT=${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres"]
    ports:
      - '5432:5432'
    restart: on-failure

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_container
    volumes:
      - ${PWD}/migrations:/flyway/sql
      - ${PWD}/docker-flyway.config:/flyway/conf/flyway.config
    env_file:
      - .env
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    depends_on:
      - postgresdb

# Named volume for the postgresdb service to store persistent data
volumes:
  postgres-data: